name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/menu.json
    - assets/images/
  fonts:
    - family: Cereal
    - family: Azo-Sans-Uber
      fonts:
        - asset: assets/fonts/cereal-regular.otf
        - asset: assets/fonts/cereal-bold.otf
        - asset: assets/fonts/Azo-Sans-Uber.ttf
